theme = "heisenberg"

[editor]
bufferline = "always"
text-width = 96
cursorline = true
rulers = [96]
true-color = true
line-number = "relative"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
center = ["version-control"]

[keys.normal]
"C-x" = ":w"

[keys.select]
"C-x" = ["normal_mode", ":w"]

[keys.insert]
"C-x" = ["normal_mode", ":w"]
