#!/bin/bash
set -e

PORT="1984"

cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
cat << 'EOF' > /etc/ssh/sshd_config
Include /etc/ssh/sshd_config.d/*.conf
AuthorizedKeysFile      .ssh/authorized_keys
Subsystem       sftp    /usr/libexec/openssh/sftp-server
EOF

cat << EOF > /etc/ssh/sshd_config.d/10-harden.conf
Protocol 2
Port $PORT
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
MaxAuthTries 3
AllowUsers ruslan
X11Forwarding no

KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
EOF

semanage port -a -t ssh_port_t -p tcp $PORT

systemctl edit --stdin sshd.socket <<EOF
[Socket]
ListenStream=$PORT
Accept=yes
EOF

systemctl daemon-reload
systemctl restart sshd

firewall-cmd --permanent --add-port=${PORT}/tcp
firewall-cmd --reload
ss -tlnp | grep sshd
