[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias hx='helix'

export LS_COLORS=$(vivid generate one-dark)
export PS1="\e[01;32m[\u@\h \W]\$ \e[m "
export PATH="$(yarn global bin):${HOME}/go/bin:${HOME}/script:$PATH"

gpgconf --kill all &> /dev/null
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye &> /dev/null

