#!/bin/sh

SRC=/data/vault
DST=/data/backup
ARC=/data/archive
MNT=$HOME/vault
STP="$(date +%y%m%d%H%M)"
RET="10"
NAM="vault"

ls $SRC $DST $MNT &>/dev/null || { echo "error: missing dirs" && exit 1; }
mountpoint -q $MNT && { echo "error: vault is mounted" && exit 1; }

if [[ $1 == "-p" ]]; then
  NAM="heritage"
fi

tar -cJvf ${DST}/${NAM}-${STP}.txz -C ${SRC%/*} ${SRC##*/}

if [[ $? == 0 ]]; then
  echo "info: success"
  C=$(ls -1 ${DST}/vault* | wc -l)
  if [[ $C -gt $RET ]]; then
    echo "info: shaving"
    rm -f $(ls -1r ${DST}/vault* | tail -n +${RET})
  fi
  if [[ $NAM == "heritage" ]]; then
    echo "info: archiving"
    mv ${DST}/heritage* $ARC
  fi
else
  echo "error: backup"
fi

