FROM docker.io/library/alpine:edge

ARG UIDN
ARG VERS
ARG NAME

LABEL name=$NAME
LABEL version=$VERS
LABEL maintainer="Nero Dicentra <nero.dicentra@gmail.com>"


RUN apk upgrade -U --no-cache
RUN apk add --no-cache sudo gnupg gocryptfs

RUN adduser -D $UIDN && addgroup $UIDN wheel
RUN mkdir -p /etc/sudoers.d && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/nopass

USER $UIDN
WORKDIR /home/$UIDN
RUN mkdir -p ~/vault ~/.vault
RUN echo 'alias vault="gocryptfs -nosyslog -q $HOME/.vault/ $HOME/vault/"' > .profile

CMD ["/bin/ash","-l"]

